import uuid
from datetime import date
from decimal import Decimal
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

#: Offered by the cardio section of the workout tab. `other` exists so the list
#: never blocks logging something it does not name.
CardioActivity = Literal[
    "run", "walk", "cycle", "swim", "row", "elliptical", "stairs", "hike", "class", "other"
]

#: Typo guards, not limits on what anyone can do: 24h and 1000km.
MAX_DURATION_MIN = 1440
MAX_DISTANCE_KM = Decimal("1000")


class CardioSessionCreate(BaseModel):
    """Body of `POST /cardio-sessions`.

    `client_uuid` is generated by the app, not the server: the offline queue
    (§8) needs the same request to be identifiable across retries, and a
    server-minted id would make every replay a new session.

    `session_date` comes from the client for the same reason every other date
    does — the server must never decide what "today" is (§6).
    """

    model_config = ConfigDict(extra="forbid")

    client_uuid: uuid.UUID
    session_date: date
    activity: CardioActivity
    duration_min: int = Field(ge=1, le=MAX_DURATION_MIN)
    #: Omitted when the activity does not measure it. Absent is "not measured",
    #: which is not the same as zero.
    distance_km: Decimal | None = Field(default=None, ge=0, le=MAX_DISTANCE_KM)
    notes: str | None = Field(default=None, max_length=2000)


class CardioSessionOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    client_uuid: uuid.UUID
    session_date: date
    activity: str
    duration_min: int
    distance_km: Decimal | None
    notes: str | None
